### ISSUE TITLE
step07에서 css_minify

### ISSUE THREAD

**Issue by ghost** [eu81273/gulp-step-by-step#3]
_src/css/main.css_ 

``` css
@import "dep.css";

/* dummy class a */
a {
    font-size: 1em;
}
```

_src/css/dep.css_

``` css
/* dummy class b */
a {
    font-size: 2em;
    color: red;
}
```

_dist/css/main.css_

``` css
a{color:red;font-size:1em}
```

최적화 병합된다는 말씀이, 같은 태그였을 때 적절하게 요소에 삽입해준다는 의미인가요ㅠ?
